"""
Mock Swiggy Data - Simulated restaurant and menu data
Mimics what would come from the Swiggy MCP Server or public API
"""

RESTAURANTS = [
    {
        "id": "rest_001",
        "name": "Domino's Pizza",
        "cuisine": ["Pizza", "Italian", "Fast Food"],
        "rating": 4.2,
        "total_ratings": 12500,
        "delivery_time": "25-30 mins",
        "delivery_fee": 40,
        "min_order": 199,
        "is_veg": False,
        "cost_for_two": 400,
        "location": "Madhapur",
        "address": "Ayyappa Society, Madhapur, Hyderabad",
        "is_open": True,
        "offers": ["50% off up to ₹100", "Free delivery on orders above ₹499"],
        "image": "🍕",
        "menu": {
            "Bestsellers": [
                {"id": "d001", "name": "Margherita Pizza", "size": "Medium", "price": 299, "is_veg": True, "description": "Classic delight with 100% real mozzarella cheese", "rating": 4.3, "bestseller": True},
                {"id": "d002", "name": "Farmhouse Pizza", "size": "Medium", "price": 399, "is_veg": True, "description": "Delightful combination of onion, capsicum, tomato & mushroom", "rating": 4.4, "bestseller": True},
                {"id": "d003", "name": "Chicken Dominator", "size": "Medium", "price": 549, "is_veg": False, "description": "Loaded with double pepper barbecue chicken, peri peri chicken, chicken tikka & grilled chicken", "rating": 4.5, "bestseller": True},
                {"id": "d004", "name": "Peppy Paneer Pizza", "size": "Medium", "price": 379, "is_veg": True, "description": "Chunky paneer with crisp capsicum and spicy red paprika", "rating": 4.2, "bestseller": True},
            ],
            "Pizzas - Veg": [
                {"id": "d005", "name": "Cheese N Corn Pizza", "size": "Medium", "price": 349, "is_veg": True, "description": "Corn & cheese with a hint of exotic herbs", "rating": 4.1},
                {"id": "d006", "name": "Veg Extravaganza", "size": "Medium", "price": 429, "is_veg": True, "description": "Loaded with crunchy onions, crisp capsicum, juicy tomatoes, mushroom & sweet corn", "rating": 4.3},
                {"id": "d007", "name": "Mexican Green Wave", "size": "Medium", "price": 449, "is_veg": True, "description": "Spicy Mexican salsa with jalapeño, capsicum, onion & tomato", "rating": 4.0},
                {"id": "d008", "name": "Margherita Pizza", "size": "Regular", "price": 149, "is_veg": True, "description": "Classic delight with 100% real mozzarella cheese", "rating": 4.3},
                {"id": "d009", "name": "Farmhouse Pizza", "size": "Large", "price": 599, "is_veg": True, "description": "Delightful combination of onion, capsicum, tomato & mushroom", "rating": 4.4},
            ],
            "Pizzas - Non Veg": [
                {"id": "d010", "name": "Pepper Barbecue Chicken", "size": "Medium", "price": 449, "is_veg": False, "description": "Pepper barbecue chicken for real meat lovers", "rating": 4.2},
                {"id": "d011", "name": "Chicken Golden Delight", "size": "Medium", "price": 479, "is_veg": False, "description": "Loaded with golden corn & succulent chicken", "rating": 4.1},
                {"id": "d012", "name": "Non Veg Supreme", "size": "Medium", "price": 569, "is_veg": False, "description": "Supreme combination of pepperoni, barbecue chicken & spicy chicken", "rating": 4.4},
            ],
            "Sides & Beverages": [
                {"id": "d013", "name": "Garlic Breadsticks", "price": 99, "is_veg": True, "description": "Freshly baked bread sticks with garlic flavour", "rating": 4.5},
                {"id": "d014", "name": "Stuffed Garlic Bread", "price": 169, "is_veg": True, "description": "Stuffed with cheese, jalapeño and herbs", "rating": 4.3},
                {"id": "d015", "name": "Chicken Wings", "price": 199, "is_veg": False, "description": "Crispy fried chicken wings with hot sauce", "rating": 4.2},
                {"id": "d016", "name": "Coca-Cola (750ml)", "price": 67, "is_veg": True, "description": "Chilled Coca-Cola", "rating": 4.0},
                {"id": "d017", "name": "Lava Cake", "price": 109, "is_veg": True, "description": "Rich, warm chocolate cake with a gooey center", "rating": 4.6, "bestseller": True},
            ],
            "Combos": [
                {"id": "d018", "name": "2 Regular Pizzas + Garlic Bread + Coke", "price": 499, "is_veg": True, "description": "Perfect meal for two", "rating": 4.4, "bestseller": True},
                {"id": "d019", "name": "1 Medium Pizza + Stuffed Garlic Bread + Coke", "price": 549, "is_veg": True, "description": "Complete solo meal", "rating": 4.3},
            ],
        },
    },
    {
        "id": "rest_002",
        "name": "Pizza Hut",
        "cuisine": ["Pizza", "Italian", "Fast Food"],
        "rating": 4.0,
        "total_ratings": 8900,
        "delivery_time": "30-35 mins",
        "delivery_fee": 35,
        "min_order": 249,
        "is_veg": False,
        "cost_for_two": 500,
        "location": "Madhapur",
        "address": "Inorbit Mall, Madhapur, Hyderabad",
        "is_open": True,
        "offers": ["Buy 1 Get 1 Free on Medium Pizzas"],
        "image": "🍕",
        "menu": {
            "Bestsellers": [
                {"id": "ph001", "name": "Margherita", "size": "Medium", "price": 279, "is_veg": True, "description": "A hugely popular classic topped with 100% mozzarella", "rating": 4.2, "bestseller": True},
                {"id": "ph002", "name": "Tandoori Paneer", "size": "Medium", "price": 449, "is_veg": True, "description": "Tandoori paneer with capsicum, red paprika & mint mayo", "rating": 4.3, "bestseller": True},
                {"id": "ph003", "name": "Chicken Supreme", "size": "Medium", "price": 529, "is_veg": False, "description": "Herbed chicken, pepperoni with fresh veggies", "rating": 4.4, "bestseller": True},
            ],
            "Veg Pizzas": [
                {"id": "ph004", "name": "Garden Fresh", "size": "Medium", "price": 329, "is_veg": True, "description": "Fresh veggies on cheesy pizza", "rating": 4.0},
                {"id": "ph005", "name": "Veggie Supreme", "size": "Medium", "price": 399, "is_veg": True, "description": "Loaded with fresh veggies and herbs", "rating": 4.1},
                {"id": "ph006", "name": "Paneer Tikka", "size": "Medium", "price": 419, "is_veg": True, "description": "Spicy paneer tikka with onions", "rating": 4.2},
            ],
            "Non-Veg Pizzas": [
                {"id": "ph007", "name": "Chicken Tikka", "size": "Medium", "price": 459, "is_veg": False, "description": "Spicy chicken tikka with onions & capsicum", "rating": 4.3},
                {"id": "ph008", "name": "Meat Feast", "size": "Medium", "price": 549, "is_veg": False, "description": "Pepperoni, chicken sausage, and spicy chicken", "rating": 4.5},
            ],
            "Sides": [
                {"id": "ph009", "name": "Garlic Bread Classic", "price": 119, "is_veg": True, "description": "Toasted bread with garlic butter", "rating": 4.3},
                {"id": "ph010", "name": "Chicken Wings (6 pcs)", "price": 249, "is_veg": False, "description": "Crispy chicken wings", "rating": 4.1},
                {"id": "ph011", "name": "Pepsi (500ml)", "price": 60, "is_veg": True, "description": "Chilled Pepsi", "rating": 3.9},
            ],
        },
    },
    {
        "id": "rest_003",
        "name": "La Pino'z Pizza",
        "cuisine": ["Pizza", "Italian", "Fast Food"],
        "rating": 4.3,
        "total_ratings": 6200,
        "delivery_time": "35-40 mins",
        "delivery_fee": 30,
        "min_order": 199,
        "is_veg": False,
        "cost_for_two": 350,
        "location": "HITEC City",
        "address": "Cyber Towers, HITEC City, Hyderabad",
        "is_open": True,
        "offers": ["20% off on orders above ₹500"],
        "image": "🍕",
        "menu": {
            "Bestsellers": [
                {"id": "lp001", "name": "Farm Fresh Pizza", "size": "Medium", "price": 299, "is_veg": True, "description": "Loaded with fresh farm vegetables", "rating": 4.4, "bestseller": True},
                {"id": "lp002", "name": "Paneer Makhani Pizza", "size": "Medium", "price": 349, "is_veg": True, "description": "Creamy paneer makhani on pizza base", "rating": 4.5, "bestseller": True},
                {"id": "lp003", "name": "Chicken BBQ Pizza", "size": "Medium", "price": 399, "is_veg": False, "description": "Smoky BBQ chicken with onions", "rating": 4.3, "bestseller": True},
            ],
            "Veg Pizzas": [
                {"id": "lp004", "name": "Margherita", "size": "Medium", "price": 199, "is_veg": True, "description": "Classic cheese pizza", "rating": 4.2},
                {"id": "lp005", "name": "Mexican Wave", "size": "Medium", "price": 329, "is_veg": True, "description": "Spicy Mexican salsa with veggies", "rating": 4.1},
                {"id": "lp006", "name": "Tandoori Paneer", "size": "Medium", "price": 369, "is_veg": True, "description": "Tandoori flavored paneer pizza", "rating": 4.3},
            ],
            "Non-Veg Pizzas": [
                {"id": "lp007", "name": "Chicken Tikka", "size": "Medium", "price": 379, "is_veg": False, "description": "Loaded with chicken tikka pieces", "rating": 4.2},
                {"id": "lp008", "name": "Keema Do Pyaza", "size": "Medium", "price": 419, "is_veg": False, "description": "Spicy keema with double onion", "rating": 4.4},
            ],
            "Sides": [
                {"id": "lp009", "name": "Cheesy Garlic Bread", "price": 89, "is_veg": True, "description": "Garlic bread loaded with cheese", "rating": 4.5},
                {"id": "lp010", "name": "Pasta Alfredo", "price": 179, "is_veg": True, "description": "Creamy white sauce pasta", "rating": 4.0},
            ],
        },
    },
    {
        "id": "rest_004",
        "name": "Meghana Foods",
        "cuisine": ["Biryani", "Andhra", "South Indian"],
        "rating": 4.5,
        "total_ratings": 25000,
        "delivery_time": "30-35 mins",
        "delivery_fee": 25,
        "min_order": 149,
        "is_veg": False,
        "cost_for_two": 500,
        "location": "Madhapur",
        "address": "Durgam Cheruvu Road, Madhapur, Hyderabad",
        "is_open": True,
        "offers": ["10% off on first order", "Free delivery on orders above ₹399"],
        "image": "🍗",
        "menu": {
            "Bestsellers": [
                {"id": "mg001", "name": "Chicken Dum Biryani", "price": 299, "is_veg": False, "description": "Aromatic basmati rice with tender chicken, slow-cooked Hyderabadi style", "rating": 4.7, "bestseller": True},
                {"id": "mg002", "name": "Andhra Chicken Curry Meals", "price": 249, "is_veg": False, "description": "Full meals with spicy Andhra chicken curry, rice, dal & pickle", "rating": 4.5, "bestseller": True},
                {"id": "mg003", "name": "Mutton Dum Biryani", "price": 399, "is_veg": False, "description": "Premium mutton biryani with aromatic spices", "rating": 4.6, "bestseller": True},
            ],
            "Biryani": [
                {"id": "mg004", "name": "Veg Dum Biryani", "price": 199, "is_veg": True, "description": "Fragrant vegetable biryani with mixed veggies", "rating": 4.2},
                {"id": "mg005", "name": "Egg Biryani", "price": 229, "is_veg": False, "description": "Egg biryani with boiled eggs & spices", "rating": 4.3},
                {"id": "mg006", "name": "Prawns Biryani", "price": 449, "is_veg": False, "description": "Coastal style prawns biryani", "rating": 4.4},
                {"id": "mg007", "name": "Paneer Dum Biryani", "price": 249, "is_veg": True, "description": "Paneer pieces in aromatic biryani", "rating": 4.1},
            ],
            "Meals": [
                {"id": "mg008", "name": "Andhra Veg Meals", "price": 179, "is_veg": True, "description": "Rice, sambar, rasam, curd, pickle & 2 curries", "rating": 4.3},
                {"id": "mg009", "name": "Chicken 65 Meals", "price": 269, "is_veg": False, "description": "Meals with crispy chicken 65", "rating": 4.4},
                {"id": "mg010", "name": "Guntur Chicken Meals", "price": 289, "is_veg": False, "description": "Spicy Guntur style chicken with meals", "rating": 4.5},
            ],
            "Starters": [
                {"id": "mg011", "name": "Chicken 65", "price": 249, "is_veg": False, "description": "Crispy, spicy deep-fried chicken", "rating": 4.6, "bestseller": True},
                {"id": "mg012", "name": "Apollo Fish", "price": 349, "is_veg": False, "description": "Andhra style spicy fried fish", "rating": 4.5},
                {"id": "mg013", "name": "Paneer 65", "price": 229, "is_veg": True, "description": "Crispy paneer bites with spices", "rating": 4.2},
                {"id": "mg014", "name": "Gobi 65", "price": 189, "is_veg": True, "description": "Crispy cauliflower fritters", "rating": 4.1},
            ],
            "Beverages": [
                {"id": "mg015", "name": "Buttermilk", "price": 49, "is_veg": True, "description": "Traditional spiced buttermilk", "rating": 4.4},
                {"id": "mg016", "name": "Sweet Lassi", "price": 79, "is_veg": True, "description": "Thick, creamy sweet lassi", "rating": 4.3},
            ],
        },
    },
    {
        "id": "rest_005",
        "name": "Empire Restaurant",
        "cuisine": ["Biryani", "North Indian", "Kebabs"],
        "rating": 4.1,
        "total_ratings": 15000,
        "delivery_time": "25-30 mins",
        "delivery_fee": 30,
        "min_order": 149,
        "is_veg": False,
        "cost_for_two": 450,
        "location": "Gachibowli",
        "address": "Biodiversity Junction, Gachibowli, Hyderabad",
        "is_open": True,
        "offers": ["Free delivery above ₹299"],
        "image": "🍖",
        "menu": {
            "Bestsellers": [
                {"id": "em001", "name": "Empire Special Biryani", "price": 329, "is_veg": False, "description": "Signature biryani with tender chicken & fragrant rice", "rating": 4.3, "bestseller": True},
                {"id": "em002", "name": "Shawarma Roll", "price": 149, "is_veg": False, "description": "Juicy chicken shawarma in a fresh wrap", "rating": 4.4, "bestseller": True},
                {"id": "em003", "name": "Butter Chicken", "price": 299, "is_veg": False, "description": "Creamy, rich butter chicken", "rating": 4.2, "bestseller": True},
            ],
            "Biryani": [
                {"id": "em004", "name": "Chicken Biryani", "price": 259, "is_veg": False, "description": "Classic chicken biryani", "rating": 4.1},
                {"id": "em005", "name": "Mutton Biryani", "price": 359, "is_veg": False, "description": "Tender mutton biryani", "rating": 4.3},
                {"id": "em006", "name": "Veg Biryani", "price": 199, "is_veg": True, "description": "Mixed vegetable biryani", "rating": 4.0},
            ],
            "Kebabs": [
                {"id": "em007", "name": "Chicken Seekh Kebab (4 pcs)", "price": 229, "is_veg": False, "description": "Minced chicken kebabs grilled to perfection", "rating": 4.3},
                {"id": "em008", "name": "Tandoori Chicken (Half)", "price": 269, "is_veg": False, "description": "Marinated and grilled in tandoor", "rating": 4.4},
                {"id": "em009", "name": "Paneer Tikka (6 pcs)", "price": 219, "is_veg": True, "description": "Grilled cottage cheese with spices", "rating": 4.1},
            ],
            "North Indian": [
                {"id": "em010", "name": "Dal Makhani", "price": 199, "is_veg": True, "description": "Creamy black lentil curry", "rating": 4.2},
                {"id": "em011", "name": "Paneer Butter Masala", "price": 249, "is_veg": True, "description": "Paneer in rich tomato gravy", "rating": 4.1},
                {"id": "em012", "name": "Butter Naan", "price": 49, "is_veg": True, "description": "Soft butter naan bread", "rating": 4.3},
                {"id": "em013", "name": "Garlic Naan", "price": 59, "is_veg": True, "description": "Naan with garlic flavor", "rating": 4.4},
            ],
        },
    },
    {
        "id": "rest_006",
        "name": "Truffles",
        "cuisine": ["Burgers", "American", "Desserts", "Continental"],
        "rating": 4.4,
        "total_ratings": 20000,
        "delivery_time": "35-40 mins",
        "delivery_fee": 35,
        "min_order": 199,
        "is_veg": False,
        "cost_for_two": 600,
        "location": "Banjara Hills",
        "address": "Road No. 12, Banjara Hills, Hyderabad",
        "is_open": True,
        "offers": ["15% off on orders above ₹600"],
        "image": "🍔",
        "menu": {
            "Bestsellers": [
                {"id": "tr001", "name": "Classic Smash Burger", "price": 299, "is_veg": False, "description": "Juicy patty with cheese, lettuce, and special sauce", "rating": 4.6, "bestseller": True},
                {"id": "tr002", "name": "Death by Chocolate", "price": 249, "is_veg": True, "description": "Rich chocolate cake with chocolate ganache & chocolate ice cream", "rating": 4.8, "bestseller": True},
                {"id": "tr003", "name": "BBQ Chicken Burger", "price": 329, "is_veg": False, "description": "Grilled chicken with BBQ sauce and coleslaw", "rating": 4.5, "bestseller": True},
            ],
            "Burgers": [
                {"id": "tr004", "name": "Veg Burger", "price": 199, "is_veg": True, "description": "Crispy veg patty with fresh veggies", "rating": 4.1},
                {"id": "tr005", "name": "Mushroom Swiss Burger", "price": 349, "is_veg": True, "description": "Sautéed mushrooms with Swiss cheese", "rating": 4.3},
                {"id": "tr006", "name": "Chicken Cheese Burger", "price": 319, "is_veg": False, "description": "Chicken patty with melted cheese", "rating": 4.4},
                {"id": "tr007", "name": "Double Patty Burger", "price": 449, "is_veg": False, "description": "Double the meat, double the fun", "rating": 4.5},
            ],
            "Pastas": [
                {"id": "tr008", "name": "Penne Arrabbiata", "price": 269, "is_veg": True, "description": "Penne in spicy tomato sauce", "rating": 4.2},
                {"id": "tr009", "name": "Chicken Alfredo Pasta", "price": 349, "is_veg": False, "description": "Creamy chicken alfredo", "rating": 4.4},
            ],
            "Desserts": [
                {"id": "tr010", "name": "Nutella Waffle", "price": 219, "is_veg": True, "description": "Crispy waffle with Nutella and ice cream", "rating": 4.5},
                {"id": "tr011", "name": "Brownie with Ice Cream", "price": 189, "is_veg": True, "description": "Warm brownie with vanilla ice cream", "rating": 4.6},
                {"id": "tr012", "name": "Cheesecake", "price": 249, "is_veg": True, "description": "New York style baked cheesecake", "rating": 4.4},
            ],
            "Beverages": [
                {"id": "tr013", "name": "Cold Coffee", "price": 149, "is_veg": True, "description": "Chilled coffee shake", "rating": 4.2},
                {"id": "tr014", "name": "Oreo Shake", "price": 179, "is_veg": True, "description": "Thick Oreo milkshake", "rating": 4.5},
            ],
        },
    },
    {
        "id": "rest_007",
        "name": "A2B - Adyar Ananda Bhavan",
        "cuisine": ["South Indian", "Sweets", "Vegetarian"],
        "rating": 4.2,
        "total_ratings": 11000,
        "delivery_time": "20-25 mins",
        "delivery_fee": 20,
        "min_order": 99,
        "is_veg": True,
        "cost_for_two": 300,
        "location": "Kukatpally",
        "address": "KPHB Colony, Kukatpally, Hyderabad",
        "is_open": True,
        "offers": ["Flat ₹50 off on orders above ₹300"],
        "image": "🥘",
        "menu": {
            "Bestsellers": [
                {"id": "a2b001", "name": "Masala Dosa", "price": 99, "is_veg": True, "description": "Crispy dosa with potato filling, served with chutney & sambar", "rating": 4.5, "bestseller": True},
                {"id": "a2b002", "name": "Mini Idli Sambar", "price": 89, "is_veg": True, "description": "Bite-sized idlis in sambar", "rating": 4.4, "bestseller": True},
                {"id": "a2b003", "name": "Filter Coffee", "price": 49, "is_veg": True, "description": "Traditional South Indian filter coffee", "rating": 4.7, "bestseller": True},
            ],
            "Dosas": [
                {"id": "a2b004", "name": "Plain Dosa", "price": 79, "is_veg": True, "description": "Crispy golden dosa", "rating": 4.3},
                {"id": "a2b005", "name": "Ghee Roast", "price": 119, "is_veg": True, "description": "Crispy dosa with generous ghee", "rating": 4.5},
                {"id": "a2b006", "name": "Mysore Masala Dosa", "price": 129, "is_veg": True, "description": "Spicy chutney masala dosa", "rating": 4.4},
                {"id": "a2b007", "name": "Rava Dosa", "price": 109, "is_veg": True, "description": "Semolina dosa with crispy texture", "rating": 4.2},
                {"id": "a2b008", "name": "Onion Uttapam", "price": 99, "is_veg": True, "description": "Thick pancake topped with onions", "rating": 4.1},
            ],
            "Idli & Vada": [
                {"id": "a2b009", "name": "Idli (2 pcs)", "price": 59, "is_veg": True, "description": "Soft steamed rice cakes", "rating": 4.3},
                {"id": "a2b010", "name": "Medu Vada (2 pcs)", "price": 69, "is_veg": True, "description": "Crispy urad dal vada", "rating": 4.2},
                {"id": "a2b011", "name": "Pongal", "price": 89, "is_veg": True, "description": "Creamy rice & lentil dish with ghee", "rating": 4.4},
            ],
            "Meals & Rice": [
                {"id": "a2b012", "name": "South Indian Meals", "price": 169, "is_veg": True, "description": "Complete thali with rice, sambar, rasam, curd & more", "rating": 4.5},
                {"id": "a2b013", "name": "Curd Rice", "price": 99, "is_veg": True, "description": "Comfort food - rice mixed with curd", "rating": 4.3},
                {"id": "a2b014", "name": "Lemon Rice", "price": 89, "is_veg": True, "description": "Tangy lemon flavored rice", "rating": 4.1},
            ],
            "Sweets": [
                {"id": "a2b015", "name": "Gulab Jamun (2 pcs)", "price": 59, "is_veg": True, "description": "Soft sweet dumplings in sugar syrup", "rating": 4.4},
                {"id": "a2b016", "name": "Mysore Pak", "price": 79, "is_veg": True, "description": "Traditional ghee sweet", "rating": 4.3},
                {"id": "a2b017", "name": "Jalebi (100g)", "price": 69, "is_veg": True, "description": "Crispy sweet spirals", "rating": 4.2},
            ],
        },
    },
    {
        "id": "rest_008",
        "name": "Behrouz Biryani",
        "cuisine": ["Biryani", "Mughlai", "North Indian"],
        "rating": 4.3,
        "total_ratings": 9500,
        "delivery_time": "40-45 mins",
        "delivery_fee": 45,
        "min_order": 249,
        "is_veg": False,
        "cost_for_two": 600,
        "location": "Jubilee Hills",
        "address": "Road No. 36, Jubilee Hills, Hyderabad",
        "is_open": True,
        "offers": ["20% off on orders above ₹599"],
        "image": "🍚",
        "menu": {
            "Bestsellers": [
                {"id": "bh001", "name": "Dum Gosht Biryani", "price": 449, "is_veg": False, "description": "Royal mutton biryani with whole spices, saffron & slow-cooked meat", "rating": 4.6, "bestseller": True},
                {"id": "bh002", "name": "Murgh Makhani Biryani", "price": 379, "is_veg": False, "description": "Butter chicken style biryani", "rating": 4.5, "bestseller": True},
                {"id": "bh003", "name": "Subz-e-Biryani", "price": 299, "is_veg": True, "description": "Royal vegetable biryani with exotic spices", "rating": 4.3, "bestseller": True},
            ],
            "Biryanis": [
                {"id": "bh004", "name": "Lazeez Bhuna Murgh Biryani", "price": 399, "is_veg": False, "description": "Spicy roasted chicken biryani", "rating": 4.4},
                {"id": "bh005", "name": "Murgh Seekh Biryani", "price": 419, "is_veg": False, "description": "Chicken seekh kebab biryani", "rating": 4.3},
                {"id": "bh006", "name": "Paneer Tikka Biryani", "price": 329, "is_veg": True, "description": "Grilled paneer in biryani", "rating": 4.2},
            ],
            "Kebabs": [
                {"id": "bh007", "name": "Murgh Malai Kebab (4 pcs)", "price": 299, "is_veg": False, "description": "Creamy chicken kebabs", "rating": 4.5},
                {"id": "bh008", "name": "Paneer Malai Kebab (4 pcs)", "price": 269, "is_veg": True, "description": "Creamy paneer kebabs", "rating": 4.2},
            ],
            "Desserts": [
                {"id": "bh009", "name": "Shahi Gulab Jamun", "price": 99, "is_veg": True, "description": "Royal sized gulab jamun", "rating": 4.4},
                {"id": "bh010", "name": "Kheer", "price": 89, "is_veg": True, "description": "Traditional rice pudding", "rating": 4.1},
            ],
        },
    },
    {
        "id": "rest_009",
        "name": "McDonald's",
        "cuisine": ["Burgers", "Fast Food", "American"],
        "rating": 4.1,
        "total_ratings": 18000,
        "delivery_time": "20-25 mins",
        "delivery_fee": 30,
        "min_order": 149,
        "is_veg": False,
        "cost_for_two": 400,
        "location": "Ameerpet",
        "address": "SR Nagar Cross Roads, Ameerpet, Hyderabad",
        "is_open": True,
        "offers": ["McSaver combos starting ₹149"],
        "image": "🍔",
        "menu": {
            "Bestsellers": [
                {"id": "mc001", "name": "McChicken Burger", "price": 149, "is_veg": False, "description": "Crispy chicken patty with mayo and lettuce", "rating": 4.3, "bestseller": True},
                {"id": "mc002", "name": "McAloo Tikki Burger", "price": 69, "is_veg": True, "description": "Potato tikki with fresh veggies", "rating": 4.4, "bestseller": True},
                {"id": "mc003", "name": "Chicken McNuggets (6 pcs)", "price": 179, "is_veg": False, "description": "Crispy golden chicken nuggets", "rating": 4.2, "bestseller": True},
            ],
            "Burgers - Veg": [
                {"id": "mc004", "name": "McVeggie", "price": 119, "is_veg": True, "description": "Veg patty with lettuce & mayo", "rating": 4.1},
                {"id": "mc005", "name": "McSpicy Paneer", "price": 179, "is_veg": True, "description": "Spicy crispy paneer burger", "rating": 4.3},
                {"id": "mc006", "name": "Veg Maharaja Mac", "price": 229, "is_veg": True, "description": "Double patty veg burger", "rating": 4.2},
            ],
            "Burgers - Non Veg": [
                {"id": "mc007", "name": "Chicken Maharaja Mac", "price": 249, "is_veg": False, "description": "Double chicken patty burger", "rating": 4.4},
                {"id": "mc008", "name": "McSpicy Chicken", "price": 189, "is_veg": False, "description": "Spicy crispy chicken burger", "rating": 4.3},
            ],
            "Sides & Fries": [
                {"id": "mc009", "name": "French Fries (Medium)", "price": 119, "is_veg": True, "description": "Golden crispy fries", "rating": 4.3},
                {"id": "mc010", "name": "Hash Browns (2 pcs)", "price": 69, "is_veg": True, "description": "Crispy potato hash browns", "rating": 4.1},
            ],
            "Beverages": [
                {"id": "mc013", "name": "Coca-Cola (Medium)", "price": 79, "is_veg": True, "description": "Chilled Coca-Cola", "rating": 4.0},
                {"id": "mc014", "name": "McFlurry Oreo", "price": 149, "is_veg": True, "description": "Soft serve with crushed Oreo", "rating": 4.5},
            ],
        },
    },
    {
        "id": "rest_010",
        "name": "Chinois",
        "cuisine": ["Chinese", "Asian", "Thai"],
        "rating": 4.0,
        "total_ratings": 5500,
        "delivery_time": "30-35 mins",
        "delivery_fee": 35,
        "min_order": 199,
        "is_veg": False,
        "cost_for_two": 500,
        "location": "Kondapur",
        "address": "Kondapur Main Road, Kondapur, Hyderabad",
        "is_open": True,
        "offers": ["15% off on first order"],
        "image": "🥡",
        "menu": {
            "Bestsellers": [
                {"id": "ch001", "name": "Chicken Manchurian", "price": 279, "is_veg": False, "description": "Indo-Chinese chicken manchurian in spicy sauce", "rating": 4.3, "bestseller": True},
                {"id": "ch002", "name": "Veg Fried Rice", "price": 189, "is_veg": True, "description": "Wok-tossed vegetable fried rice", "rating": 4.2, "bestseller": True},
                {"id": "ch003", "name": "Chicken Chilli", "price": 299, "is_veg": False, "description": "Spicy chilli chicken dry", "rating": 4.4, "bestseller": True},
            ],
            "Starters": [
                {"id": "ch004", "name": "Veg Spring Roll (4 pcs)", "price": 169, "is_veg": True, "description": "Crispy rolls with veggie filling", "rating": 4.1},
                {"id": "ch005", "name": "Chicken Lollipop (6 pcs)", "price": 249, "is_veg": False, "description": "Crispy chicken lollipops", "rating": 4.3},
                {"id": "ch006", "name": "Paneer Chilli", "price": 239, "is_veg": True, "description": "Crispy paneer in chilli sauce", "rating": 4.2},
                {"id": "ch007", "name": "Dragon Chicken", "price": 289, "is_veg": False, "description": "Spicy, crispy chicken in dragon sauce", "rating": 4.4},
            ],
            "Rice & Noodles": [
                {"id": "ch008", "name": "Chicken Fried Rice", "price": 229, "is_veg": False, "description": "Wok-tossed chicken fried rice", "rating": 4.2},
                {"id": "ch009", "name": "Veg Hakka Noodles", "price": 189, "is_veg": True, "description": "Stir-fried Hakka noodles", "rating": 4.1},
                {"id": "ch010", "name": "Chicken Hakka Noodles", "price": 239, "is_veg": False, "description": "Chicken Hakka noodles", "rating": 4.3},
                {"id": "ch011", "name": "Schezwan Fried Rice", "price": 209, "is_veg": True, "description": "Spicy Schezwan fried rice", "rating": 4.2},
            ],
            "Main Course": [
                {"id": "ch012", "name": "Veg Manchurian Gravy", "price": 219, "is_veg": True, "description": "Veggie balls in thick gravy", "rating": 4.1},
                {"id": "ch013", "name": "Sweet & Sour Chicken", "price": 289, "is_veg": False, "description": "Chicken in tangy sweet & sour sauce", "rating": 4.0},
            ],
            "Soups": [
                {"id": "ch014", "name": "Hot & Sour Soup", "price": 129, "is_veg": True, "description": "Spicy & tangy soup", "rating": 4.2},
                {"id": "ch015", "name": "Chicken Sweet Corn Soup", "price": 149, "is_veg": False, "description": "Creamy chicken corn soup", "rating": 4.3},
            ],
        },
    },
]

LOCATIONS = [
    "Madhapur", "HITEC City", "Gachibowli", "Banjara Hills", "Jubilee Hills",
    "Kukatpally", "Kondapur", "Ameerpet", "Secunderabad", "Begumpet",
    "Miyapur", "Manikonda", "LB Nagar", "Dilsukhnagar", "Charminar",
]

CUISINE_TYPES = [
    "Pizza", "Italian", "Fast Food", "Biryani", "Andhra", "South Indian",
    "Burgers", "American", "Desserts", "Continental", "Chinese", "Asian",
    "Thai", "North Indian", "Mughlai", "Kebabs", "Sweets", "Vegetarian",
]

DELIVERY_PARTNERS = [
    {"name": "Rajesh Kumar", "phone": "+91 98765 43210"},
    {"name": "Amit Singh", "phone": "+91 87654 32109"},
    {"name": "Priya Sharma", "phone": "+91 76543 21098"},
    {"name": "Vikram Patel", "phone": "+91 65432 10987"},
    {"name": "Suresh Reddy", "phone": "+91 54321 09876"},
]
